"""Read and write SIPNET ``.param`` files.

SIPNET parameter file format
----------------------------------
Space/tab-delimited, two used columns::

    parameterName  value   [changeable  min  max  sigma ...]

- Comment character: ``!``  (everything after ``!`` on a line is ignored)
- Column order is irrelevant (SIPNET reads by name, not position)
- Columns beyond the second are silently accepted (legacy 5+ column format)

Python-to-SIPNET name mapping
------------------------------
Python field names follow pySIPNET's naming convention (lower-case words,
no acronyms); SIPNET uses ``camelCase`` abbreviations. Each field's
:class:`~pysipnet.parameters.base.ParameterSpec` records its ``sipnet_name``,
and :data:`PYTHON_TO_SIPNET` is derived from those specs, so the parameter
model is the single statement of the mapping. ``tests/test_param_name_mapping.py``
states it a second time by hand so that a change is deliberate.

Unit contract
~~~~~~~~~~~~~
Values are written as-is.  For parameters with ``per_year=True`` in their
:class:`~pysipnet.parameters.base.ParameterSpec`, the value written is the
per-year rate — matching what SIPNET expects in the param file (SIPNET divides
by 365 internally).
"""

from __future__ import annotations

import math
from pathlib import Path

from pysipnet.parameters.base import get_parameter_specs
from pysipnet.parameters.model import ModelFlags, SIPNETParameters

# Maps dot-separated Python path → SIPNET param file name, from the specs.
PYTHON_TO_SIPNET: dict[str, str] = {
    path: spec.sipnet_name for path, spec in get_parameter_specs(SIPNETParameters).items()
}

# The inverse, for reading a .param file back.
SIPNET_TO_PYTHON: dict[str, str] = {v: k for k, v in PYTHON_TO_SIPNET.items()}


def _flatten(params: SIPNETParameters) -> dict[str, float]:
    """Return a flat ``{sipnet_name: value}`` dict, omitting ``None`` values."""
    result: dict[str, float] = {}
    dump = params.model_dump()
    for python_path, sipnet_name in PYTHON_TO_SIPNET.items():
        group, field = python_path.split(".", 1)
        value = dump[group][field]
        if value is not None:
            result[sipnet_name] = value
    return result


def write_param_file(
    parameters: SIPNETParameters,
    flags: ModelFlags,
    path: Path,
) -> None:
    """Write the ``.param`` file SIPNET reads its parameters from.

    Parameters left as ``None`` are omitted. Those are the ones only some
    model configurations need, so writing them unconditionally would mean
    inventing values SIPNET would then ignore.

    The flags are checked against the parameters first, so a configuration
    asking for a process whose parameters are missing fails here rather than
    inside SIPNET.

    Parameters
    ----------
    parameters:
        The full parameter set.
    flags:
        Model options for this run, used to decide which parameters are
        required.
    path:
        Where to write the file, normally ``<workdir>/sipnet.param``.
    """
    parameters.validate_for_flags(flags)
    flat = _flatten(parameters)
    lines = ["! SIPNET parameter file - generated by pySIPNET\n"]
    for sipnet_name, value in flat.items():
        # Format explicitly rather than with repr(). A numpy scalar reprs as
        # "np.float64(8.3)", which SIPNET's strtod reads as 0 without
        # complaining, and repr() also emits "nan"/"inf", which it accepts.
        # .17g round-trips a double exactly.
        numeric = float(value)
        if not math.isfinite(numeric):
            raise ValueError(
                f"Refusing to write {sipnet_name} = {value!r}: SIPNET would parse it "
                "and run to completion, producing output that looks plausible."
            )
        lines.append(f"{sipnet_name}\t{numeric:.17g}\n")
    path.write_text("".join(lines))


def read_param_file(path: Path) -> dict[str, float]:
    """Read a SIPNET ``.param`` file and return a ``{sipnet_name: value}`` dict.

    Comments (``!``) and extra columns beyond the second are ignored.
    """
    result: dict[str, float] = {}
    for line in path.read_text().splitlines():
        line = line.split("!")[0].strip()
        if not line:
            continue
        parts = line.split()
        if len(parts) < 2:
            continue
        try:
            result[parts[0]] = float(parts[1])
        except ValueError:
            continue
    return result
